### PR TITLE
Vitest 0.25.1 regression: TypeError: url.match is not a function

### PR DESCRIPTION
**Pull request by belgattitude**
After update to 0.25.0 to 0.25.1 (also present in 0.25.2), the test suite complains with

**TypeError: url.match is not a function**

### Setup: 

- happy-dom: 7.7.0 (latest)
- vite: 3.2.3 (latest)
- config used: https://github.com/belgattitude/nextjs-monorepo-example/blob/e3f1e4d58853538531f5d068a616b21a26088588/apps/nextjs-app/vitest.config.ts

### Investigation

Haven't tried on jsdom, but with happy-dom seems the url is passed as URL object, not a string. As per MDN [it should be a string](https://developer.mozilla.org/en-US/docs/Web/API/URL#constructor). 

image

### Reproduce

```bash
git clone https://github.com/belgattitude/nextjs-monorepo-example.git
cd nextjs-monorepo-example
git switch reprod-regression-vitest
yarn install
cd apps/nextjs-app
yarn test-unit
```

### Notes

CI log, see https://github.com/belgattitude/nextjs-monorepo-example/pull/2912

image

### CODE REVIEW

**Comment by belgattitude** [comment]
Closing as there's a hack
